version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '03:00'
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-minor', 'version-update:semver-patch']
